/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"
#include "math.h"

void initialize_vector(float *vector) {
  for (int i = 0; i < 10; i++) {
    vector[i] = pow(i - 10 / 2, 2);
  }
}

void calculate_positions_of_vector(float *vector) {
  for (int i = 0; i < 10; i++) {
    vector[i] = sqrt(vector[i]);
  }
}

Result analyse_vector(CLIENT *clnt, vetor *v) {
	Result *result;

	result = analyse_vector_1000(v, clnt);
	// printf("Maior: %1.f | Menor: %1.f\n", result->biggest, result->smallest);

	if (result == NULL) {
		fprintf(stderr, "Problema na chamada RPC\n");
		exit(0);
	}

	return *result;
}

int main (int argc, char *argv[]) {
	CLIENT *clnt;
	Result result;
	vetor v;

	v.vetor_val = (float*)malloc(sizeof(float) * 12);

	initialize_vector(v.vetor_val);
	calculate_positions_of_vector(v.vetor_val);

	if(argc != 2) {
		fprintf(stderr, "Uso: %s hostname\n", argv[0]);
		exit(0);
	}
	
	clnt = clnt_create(argv[1], PROG, VERSION, "udp");

	if (clnt == (CLIENT *)NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	v.vetor_len = 10;

	result = analyse_vector(clnt, &v);

	printf("O maior numero eh: %.1f\n", result.biggest);
	printf("O menor numero eh: %.1f\n", result.smallest);

	return 0;
}