/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

Result *analyse_vector_1000_svc(vetor *argp, struct svc_req *rqstp) {
	static Result result;

	printf("Requisicao feita para analise de vetor!\n");

	result.smallest = argp->vetor_val[0];
	result.biggest = argp->vetor_val[0];

	for (int i = 0; i < argp->vetor_len; i++) {
    if (argp->vetor_val[i] < result.smallest) {
      result.smallest = argp->vetor_val[i];
    }
    if (argp->vetor_val[i] > result.biggest) {
      result.biggest = argp->vetor_val[i];
    }
  }

	return &result;
}
