/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Result {
	float smallest;
	float biggest;
};
typedef struct Result Result;

typedef struct {
	u_int vetor_len;
	float *vetor_val;
} vetor;

#define PROG 77777
#define VERSION 1000

#if defined(__STDC__) || defined(__cplusplus)
#define ANALYSE_VECTOR 10
extern  Result * analyse_vector_1000(vetor *, CLIENT *);
extern  Result * analyse_vector_1000_svc(vetor *, struct svc_req *);
extern int prog_1000_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ANALYSE_VECTOR 10
extern  Result * analyse_vector_1000();
extern  Result * analyse_vector_1000_svc();
extern int prog_1000_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Result (XDR *, Result*);
extern  bool_t xdr_vetor (XDR *, vetor*);

#else /* K&R C */
extern bool_t xdr_Result ();
extern bool_t xdr_vetor ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
