/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "app.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Result *
analyse_vector_1000(vetor *argp, CLIENT *clnt)
{
	static Result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ANALYSE_VECTOR,
		(xdrproc_t) xdr_vetor, (caddr_t) argp,
		(xdrproc_t) xdr_Result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
